### ISSUE TITLE
Xcode 10, Apple Watch (arm64_32) minimum deployment

### ISSUE THREAD

**Issue by Sweefties** [tristanhimmelman/ObjectMapper#1002]
`This bundle is invalid. Applications built for more than one architecture require an iOS Deployment Target of 3.0 or later.`

You have to set the deployment target for all watchOS targets (although it says iOS) to 3.0 or higher..

By upload to App Store Connect we have one error to minimumOS deployment. It's ok after editing your info.plist file (Carthage build watchOS) to 3.0.

**Comment by KeimyPlaza** [comment]
Maybe this error is only for Xcode10 but this library must be to supported Xcode 9.X

You can change the podfile:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['WATCHOS_DEPLOYMENT_TARGET'] = '3.0'
    end
  end
end
```
Reference: https://forums.developer.apple.com/thread/108408

**Comment by callo90** [comment]
Having the same issue with carthage, any updates about this?
