### ISSUE TITLE
Xcode warns to upgrade to Swift 4.2 - new release?

### ISSUE THREAD

**Issue by Adrift001** [tristanhimmelman/ObjectMapper#1020]
### What you did:

```
pod install
```

### What you expected:

I exepected something like:

<img width="620" alt="2018-10-12 2 04 11" src="https://user-images.githubusercontent.com/8119320/46850777-c17c5f00-ce27-11e8-80c4-df073e7a5c81.png">

### What you got:

<img width="598" alt="2018-10-12 2 04 01" src="https://user-images.githubusercontent.com/8119320/46850790-c80ad680-ce27-11e8-951d-c06272cd0dea.png">

Reference:  [Update Swift Language version to 4.2 under build settings #551](https://github.com/SnapKit/SnapKit/pull/551)

**Comment by Bruno-Furtado** [comment]
+1

**Comment by sisufo** [comment]
+1

**Comment by tristanhimmelman** [comment]
This should be resolved in v3.4.1. Please let me know if not
