### ISSUE TITLE
CocoaPods specs not up to date

### ISSUE THREAD

**Issue by amg1976** [tristanhimmelman/ObjectMapper#1025]
Looks like the latest version (v3.4.0) is not yet available on CocoaPods?

https://github.com/CocoaPods/Specs/tree/master/Specs/c/a/d/ObjectMapper

**Comment by jbaez** [comment]
Same problem here. Had to point directly to master branch in git repo.
`pod 'ObjectMapper', :git => 'https://github.com/tristanhimmelman/ObjectMapper.git', :branch => 'master'`

**Comment by tristanhimmelman** [comment]
I was having an issue with the current version of Cocoapods cli that was preventing me from pushing a new version. I have resolved that now. v3.4.1 is now available on Cocoapods
