### ISSUE TITLE
Splitting the `BaseMappable` protocol to two "from JSON" and "to JSON" protocols

### ISSUE THREAD

**Issue by cuba** [tristanhimmelman/ObjectMapper#1030]
Similar to `Codable` that uses `Encodable` and `Decodable`, it would be really useful to have the protocol split so that you can now create models that are to be used ONLY for data coming FROM JSON (ie that have the `init(map: Map) throws` initializer) and models that are used for serializing TO JSON (i.e. that have the `mapping(map: Map)` method).  

This way there is compiler support for models that are supposed to be used for either requests or models that are used only for responses but never both. 

In my code I end up with models that throw runtime exceptions when I know I need to only support one way mapping but this is dangerous.

In addition, `Transforms`, `Mappable` and `ImmutableMappable` should be split up in this manner.

Personally, I care very little for `Mappable`. I feel every model should use `ImmutableMappable`. 

If this is not possible, I'll probably end up making my own mapping logic or go back to using `Codable`

**Comment by tristanhimmelman** [comment]
This type of change would require a significant rewrite of parts of the project. I do agree that it is a nice way to approach your data modelling. 

If this is something you need I would recommend using `Codable`.
