### ISSUE TITLE
Mapping Object to another Object

### ISSUE THREAD

**Issue by avjiang** [tristanhimmelman/ObjectMapper#1033]
Hi! Great Library! 

I would like to ask, can we use this Library to map properties of an object to another object that is also conforming to Mappable Protocol?

For example
```swift
     let sampleObject = SampleObject()
     sampleObject.property = "Property"

     /// Map sampleObject property value to another object with same property name
     let testObject = TestObject()
     /// testObject.property = "Property". Mapped from sampleObject
```
Thanks!

**Comment by tristanhimmelman** [comment]
Please see the following function in the Mapper class https://github.com/tristanhimmelman/ObjectMapper/blob/master/Sources/Mapper.swift#L59
