### ISSUE TITLE
How to map 2 JSONs into 1 object

### ISSUE THREAD

**Issue by mayixingkong** [tristanhimmelman/ObjectMapper#1038]
### Your JSON dictionary:

json1
{
  "name1": "ObjectMapper",
  "url1": "https://github.com/Hearst-DD/ObjectMapper"
}

json2
{
  "name2": "ObjectMapper",
  "url2": "https://github.com/Hearst-DD/ObjectMapper"
}
### Your model:

```swift
struct Repo: Mappable {
  var name: String!
  var url: URL!

  init(_ map: Map) {
    name <- map["name"]
    url <- map["url"]
  }
}

**Comment by snsdev1** [comment]
Have you solved it?

**Comment by arsalanj** [comment]
I faced a problem somewhat like this some time ago, what I did was converted the models to dict and then merge then created model from the merged dict

dictionary1.merge(dictionary2) {(current,_) in current}
--
