### ISSUE TITLE
Model to object lost data

### ISSUE THREAD

**Issue by wangergang** [tristanhimmelman/ObjectMapper#1042]
![image](https://user-images.githubusercontent.com/17979751/54247893-a13b0280-4575-11e9-8779-d671e81b4fd9.png)

为什么, 模型里面转模型的每个对象有45的数据 ,但是转成 json 的话只有6个转出来的呢?

**Comment by arsalanj** [comment]
Make sure the mapping function in the model class has proper mappings of all properties. If one is missed it might lead to data loss
