### ISSUE TITLE
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0

### ISSUE THREAD

**Issue by sanoj00b** [tristanhimmelman/ObjectMapper#1045]
After updating XCode 10.2 getting compatibility issue with swift 5.
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler: ObjectMapper.framework/Modules/ObjectMapper.swiftmodule/x86_64.swiftmodule

Please create a release for swift 5

**Comment by gim-** [comment]
I've managed to make it work on my Swift 5 project. Perhaps you need to clean your build directory (`Product -> Clean Build Folder`) before building?

**Comment by sanoj00b** [comment]
> before building?

I have tried but did not get success. is there anyone else for whom it is working?

**Comment by karlybirdkarly** [comment]
Clear Derived Data -> Clean Build Folder -> Run

**Comment by luoyinjiang** [comment]
Please create a release for swift 5

**Comment by luoyinjiang** [comment]
Follow this procedure Clear(Product -> Clean Build Folder), but did not get success

**Comment by gim-** [comment]
@luoyinjiang @sanoj00b What are you using to install the library? CocoaPods or Carthage?

**Comment by sanoj00b** [comment]
@gim-  Carthage I am using.

**Comment by gim-** [comment]
@sanoj00b Did you do `carthage build`?

**Comment by sanoj00b** [comment]
Yes
> @sanoj00b Have you done `carthage build` from a terminal?

**Comment by sanoj00b** [comment]
> @sanoj00b Have you done `carthage build` from a terminal?

Current mapped version:  "3.3.0". is it because of this?

**Comment by sanoj00b** [comment]
> > @sanoj00b Have you done `carthage build` from a terminal?
> 
> Current mapped version: "3.3.0". is it because of this?

**Comment by kublaios** [comment]
@sanoj00b Please share your solution before closing if your issue is fixed.

**Comment by sanoj00b** [comment]
@kublaios no the issue is still there. I used latest tag for repo for objectmapper as well.

**Comment by kublaios** [comment]
Okay, I came across this issue when I was using `Alamofire` and `AlamofireObjectMapper` which depends on this library. I was able to solve using the branch mentioned here: https://github.com/tristanhimmelman/AlamofireObjectMapper/issues/266#issuecomment-477661883

Of course, this is a temporary fix. The other solution would be to wait until this repo gets upgraded.
