### ISSUE TITLE
conflict with moya

### ISSUE THREAD

**Issue by luxystech** [tristanhimmelman/ObjectMapper#1046]
I have the following error http://joxi.ru/nAyXX4dfgGez62

The pod include 
pod 'Moya-ObjectMapper'
pod 'ObjectMapper', :git => 'https://github.com/alecdoconnor/ObjectMapper.git', :branch => 'Swift-4.2'

and conflict when both

**Comment by cddjr** [comment]
**pod 'ObjectMapper' **~~, :git => 'https://github.com/alecdoconnor/ObjectMapper.git', :branch => 'Swift-4.2'~~

**Comment by luxystech** [comment]
This is a miracle, yesterday cannot compile, today works fine http://joxi.ru/12MQQq3slXd4X2

Thank you

**Comment by kaleemasadmughal** [comment]
@luxystech you can close this issue.
