### ISSUE TITLE
Support Swift5

### ISSUE THREAD

**Issue by onelcat** [tristanhimmelman/ObjectMapper#1047]

**Comment by sanoj00b** [comment]
some1 has deleted my issue for the same, I do not know why? Thanks for raising it

**Comment by onelcat** [comment]
I can run normally in the Swift 5.0 project.

**Comment by IgorFedorchuk** [comment]
https://github.com/tristanhimmelman/ObjectMapper/issues/1043
Parsing complicated object with optional objects as a parameter works with workaround only

**Comment by cddjr** [comment]
**WORKAROUND**
pod 'ObjectMapper', git: 'https://github.com/cddjr/ObjectMapper.git', branch: 'swift-5'
