### ISSUE TITLE
XCODE 12.0 Could not find module 'ObjectMapper' for target 'arm64-apple-ios-simulator';

### ISSUE THREAD

**Issue by Zevsus** [tristanhimmelman/ObjectMapper#1106]
Hello! on the new version of the Xcode I use the latest and the latest version of CocoaPods.
Could not find module 'ObjectMapper' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64

**Comment by RakeshTatekonda609** [comment]
What is the solution here..?

**Comment by emrcftci** [comment]
Maybe following links can help -> 

[Apple Developer Portal](https://developer.apple.com/forums/thread/656509?answerId=634107022#634107022)
[SO answer](https://stackoverflow.com/a/63622570/793428)

**Comment by git-master101** [comment]
> Hello! on the new version of the Xcode I use the latest and the latest version of CocoaPods.
> Could not find module 'ObjectMapper' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64

Can you tell us what you did to fix this?
