### ISSUE TITLE
[Carthage][4.2.0] Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.3.1 compiler

### ISSUE THREAD

**Issue by FarziaAfroze** [tristanhimmelman/ObjectMapper#1115]
I recently updated my Xcode 11.3 (Swift 5.1.3) to Xcode 12.2 (Swift 5.3.1). Since my ObjectMapper framework was outdated, I updated it to version 4.2.0 using Carthage. But even after updating I am getting the following error: 

```swift
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.3.1 compiler: .../ObjectMapper.framework/Modules/ObjectMapper.swiftmodule/arm64-apple-ios.swiftmodule```

**Comment by FabiolaRamirez** [comment]
The same issue.

**Comment by FarziaAfroze** [comment]
The problem, in my case, was the wrong  Xcode Command line tools was selected by default. Although I was using Xcode 12.2, my command line tools was selected 11.3. Once I changed it from 'Command Line Tools' in Xcode/Preferences/Locations, and then updated carthage again, my problem was resolved.
