### ISSUE TITLE
Memory leaks when mapping an array of dictionaries nested in a parent dictionary

### ISSUE THREAD

**Issue by kylebegeman** [tristanhimmelman/ObjectMapper#435]
I am currently mapping a JSON response that returns a dictionary. The dictionary contains a key titled "games" that contains an array of dictionaries. Here is a sample JSON:

`{"games": [{"id": 1307, "status": "scheduled", "status_display": null, "stuff": [{"someStuff": 123}]}]}`

After reading this issue: #200, I removed the nested object "stuff" in order to verify this was not the issue. I am still receiving memory leaks. 

It is possible this is related to how I am processing the JSON. Here is what my mapping of the response looks like: 

`Mapper<Game>().mapArray(response.result.value!["games"])!`

Here are some shots of the instruments results: 

![screen shot 2016-04-11 at 12 53 23 am](https://cloud.githubusercontent.com/assets/1012880/14420276/10c29d1e-ff80-11e5-9837-e065f5c4f1c2.png)

![screen shot 2016-04-11 at 12 53 05 am](https://cloud.githubusercontent.com/assets/1012880/14420282/14586eae-ff80-11e5-9a6c-c3f9181c90e4.png)

Each of the snapshots that show leaks are attempts to perform the mapping. Is there a better or proper way to map JSON with this type of format? Or based on these results could it be another issue? Thanks!

**Comment by kylebegeman** [comment]
As a quick side note, creating a new parent class and adding the mappable property "games" solves this issue; however, It is preferable to not require an additional class.

**Comment by nitisha1** [comment]
@kylebegeman -i'm facing same issue with  json array of count 135000.i added generic class to map array but still there are so many memory leaks.would you please share a sample code of parent class. how did you map?
