### ISSUE TITLE
Mapping performance 

### ISSUE THREAD

**Issue by ManWithBear** [tristanhimmelman/ObjectMapper#656]
Here you can find comparison of different JSON mapping frameworks. And ObjectMapper's performance is awful. Is it problem of mapping realisation or exist some tricks for performance improvement? 
https://github.com/bwhiteley/JSONShootout

**Comment by jlyonsmith** [comment]
Damn.  After reading this I switched to [Marshal](https://github.com/utahiosmac/Marshal).  It's more verbose and not as well documented, but that's a significant performance improvement.  Sorry chaps!

**Comment by KoCMoHaBTa** [comment]
Well, I can give you a hint. Even i faced huge performance issues recently.
The example was parsing ~600 objects, which tooks ~30seconds. 
After discovering the issue and applying quick and dirty fix - i managed to reduce the time needed to ~2-3seconds. 
It turns out the Mapper calls the `mapping(map: Map)` func after `init?(map: Map)`. 
In the past, in the docs, it was written that we should call the `mapping(map: Map)` within the implementation of `init?(map: Map)`, so if we do it - the mapping is done twice which impacts the performance.
From what i see in the implementation of JSONShootout - they are using ImmutableMappable, but it could be a similar case.

**Comment by ManWithBear** [comment]
And Yes and No. ImmutableMappable call `mapping(map: Map)` after `init(map: Map)`, but because ImmutableMappable use `>>>` operator, which support mapping only TO json, mapping happen only once.

**Comment by ManWithBear** [comment]
Hm, after little research I found that you are right. 
I run same JSON like in this test. But 10 times. 
Despite of mapping from JSON, ```mapping(map: Map)``` take almost 39% time of initialization. 
After adding guard check in mapping:
```
public func mapping(map: Map) {
    guard map.mappingType == .toJSON else { return }
    ...
}
```
It decrease parsing time from 17.33s to 10.68s.

And biggest time consumer in mapping is swift_dynamicCast.
For this test biggest time take all casting to [String:Any]

**Comment by tristanhimmelman** [comment]
Thanks for bringing this to my attention. Performance is obviously a important aspect of a JSON mapping library. I have just started digging in to see what can be improved.

A couple things to note:

1. The tests in JSONShoutout are being run using `ImmutableMappable` which is a beta feature. After recreating the setup using `Mappable`, the execution time improved by 40% in my testing. 

2. The JSONShoutout tests are only being run a large JSON file (7mb). Most real life use cases will be much smaller than this (20-50 root level objects). I believe `ObjectMapper` will perform significantly better on smaller JSON data sets as it won't be casting huge amounts of data. This actually came up a while back when Swift 2 was introduced. Something changed in swift 2 which significantly decreased mapping performance for large data sets (See https://github.com/Hearst-DD/ObjectMapper/issues/251).

**Comment by ManWithBear** [comment]
1. I think it's not problem of ImmutableMappable, but framework core itself. Because my fix from previous message dive same improvement.

**Comment by tristanhimmelman** [comment]
I agree that there are likely some improvements that can be made in the core framework (with regards to casting large sets of JSON objects). 

However, there is significant room for improvement in the `ImmutableMappable` implementation as you discovered with your simple `mappingType == .toJSON` check. By skipping the execution of `mapping`, you allowed the parser to skip over repeated executions of `map["key"]`. I believe if we make the `map["key"]` function execute lazily we will see a decent improvement.

**Comment by tristanhimmelman** [comment]
It seems that another aspect that is significantly impacting mapping performance is the usage of the nested keys. When I removed that aspect for the JSONShootout test, performance improved by another 30-40%

**Comment by aehlke** [comment]
Lazy deserialization sounds very promising!

**Comment by AviDutta** [comment]
@tristanhimmelman Is there any update about getting the lazy mapping sometime soon?

**Comment by robsontenorio** [comment]
Hi!

I am experiencing some performance issues on deep nested json. Can someone, please, share some concret snippet for better performance?

**Comment by aehlke** [comment]
Switch to Codable

**Comment by robsontenorio** [comment]
@aehlke could you, please, elaborate ?

**Comment by KoCMoHaBTa** [comment]
You should start by reading the Apple guides and docs first. Codable exist for a quite long time.
- https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types
- https://developer.apple.com/documentation/swift/codable

**Comment by robsontenorio** [comment]
@KoCMoHaBTa do you advice to use native JsonDecoder + Codeable structs in favor of this ObjectMapper package ?

**Comment by KoCMoHaBTa** [comment]
Yes
