### ISSUE TITLE
Crash: Attempted to dereference garbage pointer 

### ISSUE THREAD

**Issue by danielrhodes** [tristanhimmelman/ObjectMapper#734]
I just found a crash on a production app which I traced back to using ObjectMapper's `toJSON` method. For some reason this only appeared in Release builds.

```
EXC_BAD_ACCESS: Attempted to dereference garbage pointer 0x1001f7a08.

0  xxxx            protocol witness table for xxxx.RoomAction : ObjectMapper.BaseMappable in xxxx (xxxx)
1  ObjectMapper     Mapper.toJSON(A) -> [String : Any]
2  ObjectMapper     BaseMappable.toJSON() -> [String : Any]
```

Essentially what was happening was I had a `Mappable` object which is a struct, that was passed to a function that took a `Mappable` argument like so:

```swift
foo(bar: aStructWhichIsAMappable)

private func foo(bar: Mappable) {
   bar.toJSON() //crash here.
}
```

I fixed this by defining my own `toJSON()` methods and then not coercing to `Mappable` in that function, and now there is no crash.

I'm using ObjectMapper 2.2.2

**Comment by Wooder** [comment]
I also got this kind of crash:

`Thread 0 Crashed:
0   ObjectMapper                    0xe26c6c            Mapper.toJSON(A) -> [String : Any]
1   ObjectMapper                    0xe279e8            Mapper.toJSONString(A, prettyPrint : Bool) -> String?
2   ObjectMapper                    0xe231e8            BaseMappable.toJSONString(prettyPrint : Bool) -> String?`

Anyone already working on this issue?

**Comment by Wooder** [comment]
I found a solution for this issue (the crash only happened in the release build):

Turn off "Whole Module Optimization" for the release build:

Go to Build Settings -> Optimization Level -> Select "none" for the "Release"-Target

Hope that helps.

**Comment by parbo86** [comment]
I have very similar issue, in my case changing optimization level from "Whole module" to "Single-File" fixed this crash.

**Comment by Otbivnoe** [comment]
I have the same problem ...

**Comment by tethridge** [comment]
I've been experiencing this issue as well.  When I look under build settings for optimization level, I don't see options like "whole module" or "single-file".  I only see options like "optimize for speed", "optimize for size", or "none".  Is this the same setting referenced in previous comments?  Also, this sounds like a pretty big compromise.  

Has this issue been fixed in the most recent versions?  I had been using version 2.2.  I upgraded to version 3.2 today.
