### ISSUE TITLE
Failing mapping Set<>

### ISSUE THREAD

**Issue by txaiwieser** [tristanhimmelman/ObjectMapper#735]
Using the latest build, I'm having problems making Sets in my model.

This reproduces my error, any info about this? 

```swift
    struct Test: Mappable {
        var one: String?
        var two: Set<String>?
        
        init() {}
        init?(map: Map) {}
        
        mutating func mapping(map: Map) {
            one <- map["one"]
            two <- map["two"]
        }
    }
```
```swift
        var a = Test()
        a.one = "test1"
        a.two = Set(["test2", "test3"])        
        a.toJSON() // It doesnt map the Set<String>, only the String
```

I would like to contribute if possible, just need some opinions and directions! :)
Thanks 👍

**Comment by txaiwieser** [comment]
I just found out that @tristanhimmelman was working on this couple months ago, but the branch (sets-of-basic-type) seems outdated.

Are you still working on this feature? Can I use you branch?

Thanks 👍

**Comment by tristanhimmelman** [comment]
Hey there, sorry but I never got a chance to complete that and to be honest, I'm not sure what state that branch is in. I haven't had much time to focus on ObjectMapper lately.

Feel free to try to use the branch and update it if you please.

**Comment by aehlke** [comment]
I lost a lot of time to this. Can we at least mark this as broken in the docs in the meantime?
