### ISSUE TITLE
What do you think about Codable of Swift 4?

### ISSUE THREAD

**Issue by lexrus** [tristanhimmelman/ObjectMapper#823]

**Comment by jassadakorn** [comment]
We don't need to use objectMapper anymore

**Comment by jassadakorn** [comment]
@dcortes22 Because objectMapper have to check Json key for each property in mapping function but Codable don't have to check ( [See also](https://stackoverflow.com/questions/44423309/swift-4-codable-decoding-json) ) . It's mean the key can invalid by human error

**Comment by dcortes22** [comment]
Very interesting thanks for the clarification!

**Comment by shiyizju** [comment]
With Codable, I guess the variable's name must be same as json key, and every variable will be coded into json?

**Comment by devxoul** [comment]
ObjectMapper still provides more detailed functionality.

**Comment by skydivedan** [comment]
With Codable, the property name does not need to be the same as the JSON key, you can easily map to a different name.
---
This does change things for me, though. I pour JSON into Realm objects. The main reason I use ObjectMapper is for mapping ISO8601 Strings into `Date` objects, since Realm has no mechanism to do this. I don't know what the folks at Realm think about Codable, (and I haven't thought this through yet myself!), but if Codable could be adopted in Realm, then all those DateTransforms could drop away... which might mean that I could drop ObjectMapper. 

I don't know if this is truly feasible, but something to think about.

**Comment by yariksmirnov** [comment]
I use ObjectMapper in cause of really useful support of custom transformations. In case of Realm I created my custom transformers to create-or-update objects which are referenced by ids in REST APIs.

**Comment by loudmouth** [comment]
I think the nested keypath options of ObjectMapper provide functionality that make it more adaptable to a wide variety of JSON API's. Being able to do things things like:
```
contentTypeId   <- map["contentType.sys.id"]
```

Rather than having additional nested structs is a big advantage of `ObjectMapper` for interfacing with certain APIs.

**Comment by aksswami** [comment]
But the same can be achieved via Codable and as this is the language feature, so it will be more widely used and also we have consistent parsing across most of the projects.

**Comment by Codeido** [comment]
Codable has the .toJSON() feature?

**Comment by aksswami** [comment]
Yes, Codable have `Encoder` and `Decoder` which we can use for `toJSON` and `fromJSON`.

**Comment by Codeido** [comment]
OK, but the encoder is automatic like ObjectMapper, or you have to explicit how to encode the variables?

**Comment by loudmouth** [comment]
@Codeido [here is the WWDC video](https://developer.apple.com/videos/play/wwdc2017/402/) describing "What's New in Swift"

**Comment by jonasman** [comment]
Im also planning to replace ObjectMapper in all my projects (even professional ones) with Swift4's Codable.

**Comment by emoryalimam** [comment]
here’s a great guide on using `Codable` in Swift 4: http://swiftjson.guide

**Comment by aksswami** [comment]
The best guide for `Codable` I came across:- http://benscheirman.com/2017/06/ultimate-guide-to-json-parsing-with-swift-4/

**Comment by jonasman** [comment]
I tried to convert from ObjectMapper to Codable and i must it is such a pain... OM is superior.

**Comment by guitcastro** [comment]
@jonasman Can you please elaborate why?

**Comment by tomaskraina** [comment]
For anyone still interested in the pros and cons between decodable vs ObjectMapper, I've found a nice writeup: https://medium.com/bbc-design-engineering/codable-vs-objectmapper-af5fe8e8efd5
