### ISSUE TITLE
modify the property values and set to Model

### ISSUE THREAD

**Issue by santhoshs5** [tristanhimmelman/ObjectMapper#853]
I am using ObjectMapper and Realm 

class User:Object, Mappable
{
    dynamic var name: String?
}
    func mapping(map: Map) {
        name <- map["Name"]
}

Now my question is i want to apply **removingPercentEncoding** to name before saving it model and Realm.

How can I do this?

**Comment by santhoshs5** [comment]
ObjectMapper is converting **'** is converting to some other junk charater by default.

Please recommend me best approach to do **removingPercentEncoding** from my side

**Comment by iOSUser110** [comment]
i m also looking for same thing
I want to modfiy string date into another date format String.
waiting for your responce
