### ISSUE TITLE
Mapping dictionaries with RawRepresentable keys

### ISSUE THREAD

**Issue by alexisbronchart** [tristanhimmelman/ObjectMapper#866]
Would that be possible to add mapping support for 
```
Dictionary<RawRepresentable, T: Mappable>
Dictionary<RawRepresentable, Array<T: Mappable>>
```
What would be the best way to achieve this?

**Comment by tristanhimmelman** [comment]
I think this would be possible but a significant development effort. I do not have time to take new additions to ObjectMapper at moment, but I am open to accepting this type of functionality in a Pull Request
