### ISSUE TITLE
Get error from realm when use  toJSON to transform object to json

### ISSUE THREAD

**Issue by icefox57** [tristanhimmelman/ObjectMapper#902]
Please Help me

`if let task = realmManager.objects(ModelTask.self).first {
            let json2 = task.toJSON()
            DEBUGLOG(message: json2)
            DEBUGLOG(message: tasks.id)
            DEBUGLOG(message: tasks.scenes.first?.name)
            DEBUGLOG(message: tasks.scenes.first?.actions.first?.images.first?.fileData?.count)
        }`

if i comment out             let json2 = task.toJSON()
every thing works fine. task object is saved.
but if i want to transform it to json,
get error from realm when task.toJSON() is run

Attempting to modify object outside of a write transaction - call beginWriteTransaction on an RLMRealm instance first.

### Your model:

```swift
class ModelTask: Object , Mappable{
    
    @objc dynamic var id: String = NSUUID().uuidString
    @objc dynamic var username: String = ""
    @objc dynamic var batchNumber: Int = 0
    @objc dynamic var customerCode: String = ""
    @objc dynamic var longitude: Double = 0.0
    @objc dynamic var latitude: Double = 0.0
    let scenes = List<ModelTaskScene>()
    
    required convenience init?(map: Map) {
        self.init()
    }
    
    override class func primaryKey() -> String? {
        return "id"
    }
    
    func mapping(map: Map) {
        username <- map["Username"]
        batchNumber <- map["BatchNumber"]
        customerCode <- map["CustomerCode"]
        longitude <- map["Longitude"]
        latitude <- map["Latitude"]
        try? scenes <- map["Scenes"]
    }
}
```

### What you did:

```swift
let json2 = task.toJSON()
```

### What you got:

```swift
Attempting to modify object outside of a write transaction - call beginWriteTransaction on an RLMRealm instance first.
```

**Comment by stensmir** [comment]
```Swift
 let realm = try! Realm()
 try! realm.write {
        if let JSON = realm.object(ofType:  Object.self, forPrimaryKey: id)?.toJSON() {
               debugPrint(JSON)
        }
 }
```
Work for me. But, I not sure for this way.
