### ISSUE TITLE
Mapping array with objects confronting to protocol

### ISSUE THREAD

**Issue by grzegorzkrukowski** [tristanhimmelman/ObjectMapper#909]
I'm having some hard times finding right way to parse objects that confronts to a protocol.

In my model class I do have Array of items that implements Protocol `FeedItemProtocol` - but I want to be able to parse `FeedItem` class into it (which implements both `FeedItemProtocol` and `Mappable`).

I made it work via using local variable plus `<-` operator - but I wanted to make it more clean.
Is there a way to parse array of given elements via Mapper methods from Map object ?

### Your model:

```swift
class FeedItemList: FeedItemListProtocol, Mappable {
    var total: Int!
    var items: Array<FeedItemProtocol>!

    required init?(map: Map) {
        
    }

    func mapping(map: Map) {
        total <- map["total"]

        var items: Array<FeedItem> = []
        items <- map["items"]
        self.items = items
    }
}
```

### What you did:

I'm using this as workaround:

```swift
var items: Array<FeedItem> = []
items <- map["items"]
self.items = items
```

### What you expected:

I exepected something like:

```swift
self.items = Mapper<FeedItem>().mapArray(JSONObject: map["items"].JSON)
```

**Comment by loicgriffie** [comment]
Face the same. Any idea beside the workaround or a custom transform?
