### ISSUE TITLE
How to map this part of json

### ISSUE THREAD

**Issue by GaneshShetty951** [tristanhimmelman/ObjectMapper#924]
### My JSON dictionary:

``` 
     "super_child_attributes"  : 
              { 
                 "1535"  :
                     { 
                        "is_color" : false, 
                        "ids" : 
                        { 
                            "XS" : ["12289"],
                            "S" : ["12290"], 
                            "M" : ["12291"], 
                            "L" : ["12292"], 
                            "XL" : ["12293"]
                       }
                }
       }
```

**Comment by ruddfawcett** [comment]
Sorry, @GaneshShetty951, what's your question exactly?

**Comment by GaneshShetty951** [comment]
@ruddfawcett  I am new to iOS development, I wanted to map this JSON  using ObjectMapper ?, any suggestion would be very helpful..
I tried using Dictionary but it is not working may be I'm missing something ?

**Comment by ruddfawcett** [comment]
Are you trying to map the entire `super_child_attributes` into a struct or class?

**Comment by GaneshShetty951** [comment]
@ruddfawcett I am mapping it into a class..

**Comment by ruddfawcett** [comment]
Can you share some more code?

**Comment by GaneshShetty951** [comment]
@ruddfawcett 
`
import Foundation
import ObjectMapper
class ProductScreenData : Mappable {
    var superChildAttributes : [String: Ids]?
    required init(map : Map) {
    }
    func mapping(map: Map) {
        superChildAttributes <- map["super_child_attributes"]
    }    
}

class Ids : Mappable {
    var map_attribute : [ String : [String] ]?
    var isColor : BooleanLiteralType?
    var label : String?
    
    required init?(map: Map) {
    }
    func mapping(map: Map) {
        map_attribute <- map["ids"]
        isColor <- map ["is_color"]
        label <- map ["label"]
    }
}
`
