### ISSUE TITLE
Cannot covert value of type 'Int'

### ISSUE THREAD

**Issue by ilatypov** [tristanhimmelman/ObjectMapper#925]
I get a compile error using the 8.3.3 toolset

```
/Users/USER/Home/DIR/Pods/ObjectMapper/Sources/IntegerOperators.swift:101:17: error: cannot convert value of type 'Int' to expected argument type 'IntMax' (aka 'Int64')
                return T.init(x)
                              ^
                              IntMax( )
```
https://github.com/Hearst-DD/ObjectMapper/blob/04c624cbbc4f05659605ae72db0f3e9eaf2eeeef/Sources/IntegerOperators.swift#L101

**Comment by maxgaurav** [comment]
## Description

I just install ObjectMapper on a fresh project and I too got the same error

# Xcode Settings
- Swift Version: 3

## Pod file
Following are the content of pod file
```
target 'SampleApp' do
    pod 'Alamofire', '~> 4.5'
    pod 'ObjectMapper', '~> 3.1'
end
```
## Errors
- Project/Pods/ObjectMapper/Sources/IntegerOperators.swift:101:17: Cannot convert value of type 'Int' to expected argument type 'IntMax' (aka 'Int64')
-/Users/maxgaurav/Documents/projects/ios/todo/NewTodoApp/Pods/ObjectMapper/Sources/IntegerOperators.swift:104:17: Cannot convert value of type 'Int8' to expected argument type 'IntMax' (aka 'Int64')
- Project/Pods/ObjectMapper/Sources/IntegerOperators.swift:107:17: Cannot convert value of type 'Int16' to expected argument type 'IntMax' (aka 'Int64')
- Project/Pods/ObjectMapper/Sources/IntegerOperators.swift:110:17: Cannot convert value of type 'Int32' to expected argument type 'IntMax' (aka 'Int64')
- Project/Pods/ObjectMapper/Sources/IntegerOperators.swift:129:17: Cannot convert value of type 'UInt' to expected argument type 'UIntMax' (aka 'UInt64')
- Project/Pods/ObjectMapper/Sources/IntegerOperators.swift:132:17: Cannot convert value of type 'UInt8' to expected argument type 'UIntMax' (aka 'UInt64')
- Project/Pods/ObjectMapper/Sources/IntegerOperators.swift:135:17: Cannot convert value of type 'UInt16' to expected argument type 'UIntMax' (aka 'UInt64')
- Project/Pods/ObjectMapper/Sources/IntegerOperators.swift:138:17: Cannot convert value of type 'UInt32' to expected argument type 'UIntMax' (aka 'UInt64')
