### ISSUE TITLE
Array of String contains null, it returns nil in mapping

### ISSUE THREAD

**Issue by veer-suthar** [tristanhimmelman/ObjectMapper#943]
JSON looks like.

```
"benefits": [
                "package benefits 1",
                null,
                null
            ],

```
If this is JSON, ObjectMapper returns nil, on 

`benefits <- map["benefits"]
`

**Comment by parmar-mehul** [comment]
I am facing same issue! @chatarveer 

Does anyone have Any solution? @tristanhimmelman
