### ISSUE TITLE
Swift snapshots version build error 

### ISSUE THREAD

**Issue by networkextension** [tristanhimmelman/ObjectMapper#945]
Swift version 
https://swift.org/builds/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2018-02-08-a/swift-DEVELOPMENT-SNAPSHOT-2018-02-08-a-osx.pkg

"""
/Users/yarshure/Desktop/ObjectMapper/Sources/TransformOperators.swift:58:13: error: invalid redeclaration of '<-'
public func <- <Transform: TransformType>(left: inout Transform.Object!, right: (Map, Transform)) {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/TransformOperators.swift:36:13: note: '<-' previously declared here
public func <- <Transform: TransformType>(left: inout Transform.Object?, right: (Map, Transform)) {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/TransformOperators.swift:115:13: error: invalid redeclaration of '<-'
public func <- <Transform: TransformType>(left: inout [Transform.Object]!, right: (Map, Transform)) {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/TransformOperators.swift:93:13: note: '<-' previously declared here
public func <- <Transform: TransformType>(left: inout [Transform.Object]?, right: (Map, Transform)) {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/TransformOperators.swift:172:13: error: invalid redeclaration of '<-'
public func <- <Transform: TransformType>(left: inout [String: Transform.Object]!, right: (Map, Transform)) {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/TransformOperators.swift:150:13: note: '<-' previously declared here
public func <- <Transform: TransformType>(left: inout [String: Transform.Object]?, right: (Map, Transform)) {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/TransformOperators.swift:231:13: error: invalid redeclaration of '<-'
public func <- <Transform: TransformType>(left: inout Transform.Object!, right: (Map, Transform)) where Transform.Object: BaseMappable {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/TransformOperators.swift:209:13: note: '<-' previously declared here
public func <- <Transform: TransformType>(left: inout Transform.Object?, right: (Map, Transform)) where Transform.Object: BaseMappable {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/TransformOperators.swift:288:13: error: invalid redeclaration of '<-'
public func <- <Transform: TransformType>(left: inout Dictionary<String, Transform.Object>!, right: (Map, Transform)) where Transform.Object: BaseMappable {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/TransformOperators.swift:268:13: note: '<-' previously declared here
public func <- <Transform: TransformType>(left: inout Dictionary<String, Transform.Object>?, right: (Map, Transform)) where Transform.Object: BaseMappable {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/TransformOperators.swift:371:13: error: invalid redeclaration of '<-'
public func <- <Transform: TransformType>(left: inout Dictionary<String, [Transform.Object]>!, right: (Map, Transform)) where Transform.Object: BaseMappable {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/TransformOperators.swift:335:13: note: '<-' previously declared here
public func <- <Transform: TransformType>(left: inout Dictionary<String, [Transform.Object]>?, right: (Map, Transform)) where Transform.Object: BaseMappable {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/TransformOperators.swift:439:13: error: invalid redeclaration of '<-'
public func <- <Transform: TransformType>(left: inout Array<Transform.Object>!, right: (Map, Transform)) where Transform.Object: BaseMappable {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/TransformOperators.swift:417:13: note: '<-' previously declared here
public func <- <Transform: TransformType>(left: inout Array<Transform.Object>?, right: (Map, Transform)) where Transform.Object: BaseMappable {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/TransformOperators.swift:509:13: error: invalid redeclaration of '<-'
public func <- <Transform: TransformType>(left: inout [[Transform.Object]]!, right: (Map, Transform)) {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/TransformOperators.swift:481:13: note: '<-' previously declared here
public func <- <Transform: TransformType>(left: inout [[Transform.Object]]?, right: (Map, Transform)) {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/TransformOperators.swift:576:13: error: invalid redeclaration of '<-'
public func <- <Transform: TransformType>(left: inout Set<Transform.Object>!, right: (Map, Transform)) where Transform.Object: BaseMappable {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/TransformOperators.swift:551:13: note: '<-' previously declared here
public func <- <Transform: TransformType>(left: inout Set<Transform.Object>?, right: (Map, Transform)) where Transform.Object: BaseMappable {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/EnumOperators.swift:35:13: error: invalid redeclaration of '<-'
public func <- <T: RawRepresentable>(left: inout T!, right: Map) {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/EnumOperators.swift:25:13: note: '<-' previously declared here
public func <- <T: RawRepresentable>(left: inout T?, right: Map) {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/EnumOperators.swift:62:13: error: invalid redeclaration of '<-'
public func <- <T: RawRepresentable>(left: inout [T]!, right: Map) {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/EnumOperators.swift:52:13: note: '<-' previously declared here
public func <- <T: RawRepresentable>(left: inout [T]?, right: Map) {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/EnumOperators.swift:89:13: error: invalid redeclaration of '<-'
public func <- <T: RawRepresentable>(left: inout [String: T]!, right: Map) {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/EnumOperators.swift:79:13: note: '<-' previously declared here
public func <- <T: RawRepresentable>(left: inout [String: T]?, right: Map) {
            ^
/Users/yarshure/Desktop/ObjectMapper/Sources/IntegerOperators.swift:38:13: error: invalid redeclaration of '<-'
public func <- <T: SignedInteger>(left: inout T!, right: Map) {
            ^
"""

**Comment by tristanhimmelman** [comment]
This should resolved. please let me know if not.
