### ISSUE TITLE
Immutable Mapping not honoring includeNilValues in some cases

### ISSUE THREAD

**Issue by cody1024d** [tristanhimmelman/ObjectMapper#956]
When using an ImmutableMappable, the following method gets called, when trying to serialize an optional object (in the ToJson.swift file)

```swift
class func optionalObject<N: BaseMappable>(_ field: N?, map: Map) {
		if let field = field {
			object(field, map: map)
		}
	}
```

As you see here it is checking if the field is nil, and if it is, it doesn't include it.  This should probably honor the includeNils property on the map, and if it's on, then should serialize a null.

**Comment by savage7** [comment]
Changing it to this works:
`	
class func optionalObject<N: BaseMappable>(_ field: N?, map: Map) {
		if let field = field {
			object(field, map: map)
        } else if map.shouldIncludeNilValues {
            basicType(NSNull(), map: map) 
        }
}
`

**Comment by cody1024d** [comment]
Yep that was my exact idea for a solution, as well, thanks ya'll!
