### ISSUE TITLE
Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1.

### ISSUE THREAD

**Issue by YTSmile** [tristanhimmelman/ObjectMapper#957]
Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1: when I use Xcode 9.3 .how can I resolve it ?

**Comment by alexpersian** [comment]
Deleting your derived data should address this issue.

**Comment by nevyhostenyv** [comment]
But there is a lot of warnings of type ".../EnumOperators.swift:35:13: Invalid redeclaration of '<-' which differs only by the kind of optional passed as an inout argument ('T!' vs. 'T?')"
How can we solve it?

**Comment by croyneaus4u** [comment]
@nevyhostenyv I am facing the same issue ..

**Comment by zeusent** [comment]
Any idea how to fix these warnings?
