### ISSUE TITLE
Invalid Redeclaration Warnings with Swift 4.x & Xcode 9.3

### ISSUE THREAD

**Issue by DevPravin** [tristanhimmelman/ObjectMapper#967]
Hi Team,

I am using Xcode 9.3 and added this lib using pod. When I tried to build, found warnings, PFA error screen shot showing warnings.
Could you please resolve this? Is there any Swift 4.x specific branch is available?
<img width="1512" alt="error_objectmapper" src="https://user-images.githubusercontent.com/20066655/40113182-330ad326-5926-11e8-8950-9d52a029eb53.png">

**Comment by Gerst20051** [comment]
Same here looks like this project isn't being maintained anymore.

**Comment by DevPravin** [comment]
Thank you, this helps 👍

**Comment by phoney** [comment]
This is a duplicate issue of https://github.com/Hearst-DD/ObjectMapper/issues/961

**Comment by liamnichols** [comment]
FYI this a compile error in Xcode 10 beta 1 (and it's new build system)

<img width="974" alt="screen shot 2018-06-04 at 21 47 08" src="https://user-images.githubusercontent.com/482871/40940822-e454764a-6840-11e8-846a-7fe7262c5744.png">

**Comment by croyneaus4u** [comment]
I can see a PR pending for the above issue:
#976

**Comment by joshwoods** [comment]
Is there any timeline to be getting a fix in for this? I would like to be moving forward using Xcode 10 to prep for iOS 12, however, this is making it so I cannot even compile our main app. Thanks in advance!

**Comment by pmusolino** [comment]
News?

**Comment by gcharita** [comment]
#980 fixed this in Xcode 10.

Warnings in Xcode Xcode 9.3 and 9.4 will remain due to the fact that the behavior of IUO is not the same as Xcode 10 and as a result compilation fails in test targets.
