### ISSUE TITLE
Problem to compile in Xcode 10 beta for version 2.2.9

### ISSUE THREAD

**Issue by zhouhao27** [tristanhimmelman/ObjectMapper#988]
Got a lot of compiling error messages like:

> Invalid redeclaration of '<-'

> Invalid redeclaration of 'optionalBasicType(_:object:)'

I want to still use Swift 3 so that I'm using ObjectMapper 2.2.9. Any idea? Thanks.

**Comment by gcharita** [comment]
@zhouhao27 just install the latest version.

**Comment by zhouhao27** [comment]
@gcharita The latest version is for Swift 4, right? I'm still using Swift 3 in my project.

**Comment by zhouhao27** [comment]
Actually there is another reason I still need to use 2.2.9. The AlamofireObjectMapper is depends on this for Swift 3.

**Comment by gcharita** [comment]
@zhouhao27 since Xcode 9 you can have different swift versions per target.
So, you can have swift 4 pods in a swift 3 project.
Having said that, just install the latest version of `AlamofireObjectMapper` and you are good to go.

Keep in mind though, that, as Apple [mentioned in WWDC 2018](https://developer.apple.com/videos/play/wwdc2018/401/), Xcode 10 is tha last Xcode version that support swift 3.

**Comment by zhouhao27** [comment]
@gcharita Here is the screenshots for my demo project using `AlamofireObjectMapper`. 

<img width="632" alt="screenshot 2018-08-12 at 11 10 54 pm" src="https://user-images.githubusercontent.com/8099731/44003426-20be5360-9e85-11e8-9e40-c6887471e4e9.png">

I can't find any target for Swift 3.

**Comment by gcharita** [comment]
@zhouhao27 in this screenshot you can see the target of the project (you can keep this in swift 3)

![screen shot 2018-08-20 at 13 54 22](https://user-images.githubusercontent.com/16266885/44336909-973e9e80-a481-11e8-8c4e-1786e2f25d6f.png)

And in this screenshot is the target of the ObjectMapper (swift 4)
![screen shot 2018-08-20 at 13 55 17](https://user-images.githubusercontent.com/16266885/44336935-b0dfe600-a481-11e8-8949-b3a041fe958b.png)

**Comment by zhouhao27** [comment]
@gcharita So that means I can use library in Pods in Swift 4 and still keep my project in swift 3? Thanks.

**Comment by gcharita** [comment]
@zhouhao27 if the installation of the latest version fixed the compiler errors, please close this issue.

**Comment by tristanhimmelman** [comment]
This should be resolved
